apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tomahawk
  name: tomahawk
spec:
  containers:
  - image: nginx
    name: tomahawk
    resources: {}
    ports:
    - name: metrics
      containerPort: 8080
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
