apiVersion: v1
data:
  test.html: |
    {{template "head" .}}
    {{template "prom_content_head" .}}
    <h1>LimeDrop Web Server Metrics</h1>

    <strong>Server Status:</strong> {{ template "prom_query_drilldown" (args "up{job='Web Server'}") }}
    <br />
    <br />
    <strong>Current CPU Usage:</strong> {{ template "prom_query_drilldown" (args "sum(rate(node_cpu_seconds_total{instance='limedrop-web:9100',mode!='idle'}[5m])) * 100 / 2" "%") }}
    <br />
    <br />
    <strong>Current Memory Usage:</strong> {{ template "prom_query_drilldown" (args "100 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100" "%") }}
    {{template "prom_content_tail" .}}
    {{template "tail"}}
kind: ConfigMap
metadata:
  name: consoles
