apiVersion: v1
data:
  test.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Pod Resource Usage</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                padding: 20px;
            }
            h1 {
                color: #333;
            }
            .graph-container {
                margin-bottom: 40px;
            }
            .graph {
                width: 100%;
                height: 300px;
                border: 1px solid #ccc;
            }
        </style>
    </head>
    <body>

        <h1>Pod Resource Usage</h1>

        <div class="graph-container">
            <h2>Memory Usage Over Time</h2>
            <div class="graph">
                <iframe 
                    src="/graph?g0.expr=container_memory_usage_bytes%7Bpod%3D%22tomahawk%22%7D&g0.tab=0&g0.stacked=0&g0.range_input=1h" 
                    frameborder="0" 
                    width="100%" 
                    height="300">
                </iframe>
            </div>
        </div>

        <div class="graph-container">
            <h2>CPU Usage Over Time</h2>
            <div class="graph">
                <iframe 
                    src="/graph?g0.expr=rate(container_cpu_usage_seconds_total%7Bpod%3D%22tomahawk%22%7D%5B5m%5D)&g0.tab=0&g0.stacked=0&g0.range_input=1h" 
                    frameborder="0" 
                    width="100%" 
                    height="300">
                </iframe>
            </div>
        </div>

    </body>
  </html>
kind: ConfigMap
metadata:
  name: consoles
