apiVersion: v1
# sum(rate(process_cpu_seconds_total{pod="rabbitns"}[1m])) by (pod)
data:
  test.html: |
    {{template "head" .}}
    {{template "prom_content_head" .}}
    <h1>Server Metrics</h1>

    <strong>Server Status:</strong> {{ template "prom_query_drilldown" (args "up{pod='rabbitns'}") }}
    <br />
    <br />

        <strong>Memory Usage Over Time</strong>
        <div class="graph">
            <iframe 
                src="/graph?g0.expr=process_virtual_memory_bytes%7Bpod%3D%22rabbitns%22%7D&g0.tab=0&g0.stacked=0&g0.range_input=2h" 
                width="100%" 
                height="300">
            </iframe>
        </div>

    <br />
    <br />

        <strong>Memory Usage Over Time</strong>
        <script>
        new PromConsole.Graph({
          node: document.querySelector("#cpuGraph"),
          expr: "sum(rate(process_cpu_seconds_total{pod="rabbitns"}[1m])) by (pod)"
        })
        </script>

    {{template "prom_content_tail" .}}
    {{template "tail"}}
kind: ConfigMap
metadata:
  name: consoles
