resources:
  # - bundle.yaml # create bundle separately first
- cm.yaml
- rbac.yaml # prometheus needs access to k8s api
- example-app/
- kube-state-metrics/
  # - example-svc-monitor.yaml # operator crd for prometheus instance
# - example-pod-monitor.yaml
- prometheus-instance.yaml
# - namespaced-pod-monitor.yaml
- nodeport.yaml # exposing with a NodePort service
- grafana/
