resources:
- prometheus_operator.yaml # using prometheus operator reduces technical overhead
- rbac.yaml # prometheus needs access to k8s api
- prometheus_instance.yaml # operator crd for prometheus instance
