apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: monitorns
  namespace: myns
  labels:
    team: frontend
spec:
  selector:
    matchLabels: {}
  podMetricsEndpoints:
  - port: metrics-port
