apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus

  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  probeNamespaceSelector: {}
  probeSelector: {}
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  ruleNamespaceSelector: {}
  ruleSelector: {}
  scrapeConfigNamespaceSelector: {}
  scrapeConfigSelector: {}
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}

  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
  podMonitorNamespaceSelector: {}
  configMaps: # The ConfigMaps are mounted into /etc/prometheus/configmaps/<configmap-name> in the 'prometheus' container.
    - consoles
  containers: # strategic merge patch the destination of the configMap mountPath to the default console template path
  - name: prometheus
    volumeMounts:
    - mountPath: /etc/prometheus/consoles
      name: configmap-consoles

  # podMonitorNamespaceSelector: {}
  # podMonitorSelector: {}
  # probeNamespaceSelector: {}
  # probeSelector: {}
  # replicas: 2
  # resources:
  #   requests:
  #     memory: 400Mi
  # ruleNamespaceSelector: {}
  # ruleSelector: {}
  # scrapeConfigNamespaceSelector: {}
  # scrapeConfigSelector: {}
  # securityContext:
  #   fsGroup: 2000
  #   runAsNonRoot: true
  #   runAsUser: 1000
  # serviceAccountName: prometheus-k8s
  # serviceMonitorNamespaceSelector: {}
  # serviceMonitorSelector: {}
  # version: 2.54.0
