apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  # OPTION 1 - select pods
  podMonitorSelector:
    matchLabels:
      team: frontend
  # OPTION 2 - select svc
  # serviceMonitorSelector:
  #   matchLabels:
  #     team: frontend
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
  podMonitorNamespaceSelector: {}
  configMaps: # The ConfigMaps are mounted into /etc/prometheus/configmaps/<configmap-name> in the 'prometheus' container.
    - consoles
  # broken
  additionalArgs:
    - name: "web.console.templates"
      value: "/etc/prometheus/configmaps/consoles/"
