apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kube-state-metrics-clusterRole.yaml
- kube-state-metrics-clusterRoleBinding.yaml
- kube-state-metrics-deployment.yaml
- kube-state-metrics-networkPolicy.yaml
- kube-state-metrics-prometheusRule.yaml
- kube-state-metrics-service.yaml
- kube-state-metrics-serviceAccount.yaml
- kube-state-metrics-serviceMonitor.yaml
